steps:
  - name: "gcr.io/k8s-skaffold/pack"
    entrypoint: "pack"
    args:
      - "build"
      - "gcr.io/$PROJECT_ID/github.com/seanfite/petersml:$COMMIT_SHA"
      - "--builder"
      - "gcr.io/buildpacks/builder:latest"
      - "--network"
      - "cloudbuild"
      - "--publish"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "services"
      - "update"
      - "peters-ml"
      - "--region=us-west1"
      - "--image=gcr.io/$PROJECT_ID/github.com/seanfite/petersml:$COMMIT_SHA"
      - "--quiet"

options:
  logging: CLOUD_LOGGING_ONLY
  